services:
  app:
    image: vidyootsenthil/notes:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - RUST_LOG=info
    depends_on:
      - db
    networks:
      - notes-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vidyootsenthil
      - POSTGRES_DB=notes
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notes-network

volumes:
  postgres_data:

networks:
  notes-network:
    driver: bridge
