services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80" # nginx port
      - "8080:8080" # backend port
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/notes
      - RUST_LOG=info
    depends_on:
      - db
    networks:
      - notes-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notes-network

volumes:
  postgres_data:

networks:
  notes-network:
    driver: bridge
